
import { PropertyType, HeaderType, DataType } from "./types";

export const columns: PropertyType[] = ["id", "first_name", "last_name", "email", "gender", "ip_address"]
export const header : HeaderType = {
    id: "ID",
    email: "Email",
    first_name: "First Name",
    last_name: "Last Name",
    gender: "Gender",
    ip_address: "IP Address"
}

export const data: DataType[] = [{
    "id": 1,
    "first_name": "Lucien",
    "last_name": "Crockford",
    "email": "lcrockford0@geocities.jp",
    "gender": "Male",
    "ip_address": "88.177.29.192"
  }, {
    "id": 2,
    "first_name": "Wallace",
    "last_name": "Erickson",
    "email": "werickson1@boston.com",
    "gender": "Male",
    "ip_address": "2.195.101.13"
  }, {
    "id": 3,
    "first_name": "Car",
    "last_name": "Harriot",
    "email": "charriot2@wp.com",
    "gender": "Male",
    "ip_address": "78.186.101.152"
  }, {
    "id": 4,
    "first_name": "Reynolds",
    "last_name": "Clapp",
    "email": "rclapp3@seesaa.net",
    "gender": "Male",
    "ip_address": "71.210.232.4"
  }, {
    "id": 5,
    "first_name": "Alard",
    "last_name": "Batchelar",
    "email": "abatchelar4@soup.io",
    "gender": "Male",
    "ip_address": "8.230.187.115"
  }, {
    "id": 6,
    "first_name": "Haroun",
    "last_name": "Goneau",
    "email": "hgoneau5@google.co.uk",
    "gender": "Male",
    "ip_address": "81.6.56.215"
  }, {
    "id": 7,
    "first_name": "Guy",
    "last_name": "Mithan",
    "email": "gmithan6@wisc.edu",
    "gender": "Male",
    "ip_address": "44.123.68.65"
  }, {
    "id": 8,
    "first_name": "Bobinette",
    "last_name": "McOrkil",
    "email": "bmcorkil7@bluehost.com",
    "gender": "Female",
    "ip_address": "181.200.180.143"
  }, {
    "id": 9,
    "first_name": "Zacharie",
    "last_name": "Crain",
    "email": "zcrain8@webmd.com",
    "gender": "Male",
    "ip_address": "235.150.117.106"
  }, {
    "id": 10,
    "first_name": "Tadio",
    "last_name": "Langthorne",
    "email": "tlangthorne9@blogspot.com",
    "gender": "Male",
    "ip_address": "103.7.165.250"
  }, {
    "id": 11,
    "first_name": "Constanta",
    "last_name": "Carnock",
    "email": "ccarnocka@pcworld.com",
    "gender": "Female",
    "ip_address": "15.184.79.214"
  }, {
    "id": 12,
    "first_name": "Peterus",
    "last_name": "Shirtcliffe",
    "email": "pshirtcliffeb@admin.ch",
    "gender": "Male",
    "ip_address": "34.242.161.253"
  }, {
    "id": 13,
    "first_name": "Morten",
    "last_name": "Surmeyers",
    "email": "msurmeyersc@posterous.com",
    "gender": "Male",
    "ip_address": "155.54.2.233"
  }, {
    "id": 14,
    "first_name": "Tadd",
    "last_name": "Gritton",
    "email": "tgrittond@wiley.com",
    "gender": "Male",
    "ip_address": "33.46.0.206"
  }, {
    "id": 15,
    "first_name": "Hieronymus",
    "last_name": "Pietri",
    "email": "hpietrie@ow.ly",
    "gender": "Male",
    "ip_address": "185.33.53.37"
  }, {
    "id": 16,
    "first_name": "Lizbeth",
    "last_name": "Ireson",
    "email": "liresonf@twitpic.com",
    "gender": "Female",
    "ip_address": "140.77.10.122"
  }, {
    "id": 17,
    "first_name": "Batsheva",
    "last_name": "Backshaw",
    "email": "bbackshawg@illinois.edu",
    "gender": "Female",
    "ip_address": "130.220.89.192"
  }, {
    "id": 18,
    "first_name": "Wilfrid",
    "last_name": "Godley",
    "email": "wgodleyh@parallels.com",
    "gender": "Male",
    "ip_address": "190.92.16.122"
  }, {
    "id": 19,
    "first_name": "Ginger",
    "last_name": "Hillyatt",
    "email": "ghillyatti@123-reg.co.uk",
    "gender": "Male",
    "ip_address": "171.173.46.32"
  }, {
    "id": 20,
    "first_name": "Marshall",
    "last_name": "Hunter",
    "email": "mhunterj@creativecommons.org",
    "gender": "Male",
    "ip_address": "168.4.175.2"
  }, {
    "id": 21,
    "first_name": "Mildrid",
    "last_name": "O'Kuddyhy",
    "email": "mokuddyhyk@java.com",
    "gender": "Female",
    "ip_address": "196.125.217.40"
  }, {
    "id": 22,
    "first_name": "Dalila",
    "last_name": "Dade",
    "email": "ddadel@behance.net",
    "gender": "Female",
    "ip_address": "124.107.62.159"
  }, {
    "id": 23,
    "first_name": "Kristin",
    "last_name": "Izac",
    "email": "kizacm@nytimes.com",
    "gender": "Female",
    "ip_address": "17.184.91.14"
  }, {
    "id": 24,
    "first_name": "Skip",
    "last_name": "Harse",
    "email": "sharsen@g.co",
    "gender": "Male",
    "ip_address": "160.55.57.177"
  }, {
    "id": 25,
    "first_name": "Khalil",
    "last_name": "Bruton",
    "email": "kbrutono@ca.gov",
    "gender": "Male",
    "ip_address": "189.242.36.194"
  }, {
    "id": 26,
    "first_name": "Cob",
    "last_name": "Suart",
    "email": "csuartp@scientificamerican.com",
    "gender": "Male",
    "ip_address": "20.131.200.237"
  }, {
    "id": 27,
    "first_name": "Michelina",
    "last_name": "Tofts",
    "email": "mtoftsq@wp.com",
    "gender": "Female",
    "ip_address": "81.186.114.67"
  }, {
    "id": 28,
    "first_name": "Percival",
    "last_name": "Larmuth",
    "email": "plarmuthr@howstuffworks.com",
    "gender": "Male",
    "ip_address": "253.239.21.203"
  }, {
    "id": 29,
    "first_name": "Lucia",
    "last_name": "Prowting",
    "email": "lprowtings@smh.com.au",
    "gender": "Female",
    "ip_address": "108.164.113.24"
  }, {
    "id": 30,
    "first_name": "Kip",
    "last_name": "Bogays",
    "email": "kbogayst@guardian.co.uk",
    "gender": "Female",
    "ip_address": "33.9.119.196"
  }, {
    "id": 31,
    "first_name": "Chantal",
    "last_name": "Branton",
    "email": "cbrantonu@dedecms.com",
    "gender": "Female",
    "ip_address": "0.43.195.236"
  }, {
    "id": 32,
    "first_name": "Edeline",
    "last_name": "Aumerle",
    "email": "eaumerlev@sbwire.com",
    "gender": "Female",
    "ip_address": "60.113.209.164"
  }, {
    "id": 33,
    "first_name": "Wheeler",
    "last_name": "Inglesent",
    "email": "winglesentw@ed.gov",
    "gender": "Male",
    "ip_address": "1.36.174.178"
  }, {
    "id": 34,
    "first_name": "Allayne",
    "last_name": "Laphorn",
    "email": "alaphornx@msn.com",
    "gender": "Male",
    "ip_address": "108.185.156.173"
  }, {
    "id": 35,
    "first_name": "Sharona",
    "last_name": "Chater",
    "email": "schatery@rediff.com",
    "gender": "Female",
    "ip_address": "42.24.86.187"
  }, {
    "id": 36,
    "first_name": "Ezri",
    "last_name": "McVey",
    "email": "emcveyz@toplist.cz",
    "gender": "Male",
    "ip_address": "195.111.92.15"
  }, {
    "id": 37,
    "first_name": "Lodovico",
    "last_name": "Colton",
    "email": "lcolton10@ft.com",
    "gender": "Male",
    "ip_address": "73.138.26.9"
  }, {
    "id": 38,
    "first_name": "Gwendolen",
    "last_name": "Linnane",
    "email": "glinnane11@bigcartel.com",
    "gender": "Female",
    "ip_address": "60.171.9.131"
  }, {
    "id": 39,
    "first_name": "Damiano",
    "last_name": "Ilyas",
    "email": "dilyas12@who.int",
    "gender": "Male",
    "ip_address": "2.79.236.80"
  }, {
    "id": 40,
    "first_name": "Val",
    "last_name": "Cakebread",
    "email": "vcakebread13@google.es",
    "gender": "Female",
    "ip_address": "221.30.68.161"
  }, {
    "id": 41,
    "first_name": "Corena",
    "last_name": "Gillingham",
    "email": "cgillingham14@networksolutions.com",
    "gender": "Female",
    "ip_address": "73.247.252.144"
  }, {
    "id": 42,
    "first_name": "Krishnah",
    "last_name": "Durtnell",
    "email": "kdurtnell15@woothemes.com",
    "gender": "Male",
    "ip_address": "249.110.115.129"
  }, {
    "id": 43,
    "first_name": "Amberly",
    "last_name": "Dillingstone",
    "email": "adillingstone16@topsy.com",
    "gender": "Female",
    "ip_address": "46.149.209.67"
  }, {
    "id": 44,
    "first_name": "Frederick",
    "last_name": "Sidle",
    "email": "fsidle17@free.fr",
    "gender": "Male",
    "ip_address": "229.245.5.255"
  }, {
    "id": 45,
    "first_name": "Arabele",
    "last_name": "Balam",
    "email": "abalam18@prnewswire.com",
    "gender": "Female",
    "ip_address": "213.12.69.116"
  }, {
    "id": 46,
    "first_name": "Arnuad",
    "last_name": "Skylett",
    "email": "askylett19@thetimes.co.uk",
    "gender": "Male",
    "ip_address": "201.82.68.19"
  }, {
    "id": 47,
    "first_name": "Pietro",
    "last_name": "Georger",
    "email": "pgeorger1a@cbc.ca",
    "gender": "Male",
    "ip_address": "193.242.132.176"
  }, {
    "id": 48,
    "first_name": "Rozele",
    "last_name": "Torregiani",
    "email": "rtorregiani1b@china.com.cn",
    "gender": "Female",
    "ip_address": "70.47.60.188"
  }, {
    "id": 49,
    "first_name": "Adrian",
    "last_name": "Gonnel",
    "email": "agonnel1c@de.vu",
    "gender": "Male",
    "ip_address": "142.130.246.230"
  }, {
    "id": 50,
    "first_name": "Janek",
    "last_name": "Gounot",
    "email": "jgounot1d@google.com.au",
    "gender": "Male",
    "ip_address": "103.117.152.193"
  }, {
    "id": 51,
    "first_name": "Abrahan",
    "last_name": "Freestone",
    "email": "afreestone1e@t-online.de",
    "gender": "Male",
    "ip_address": "214.190.160.4"
  }, {
    "id": 52,
    "first_name": "Jack",
    "last_name": "Ayris",
    "email": "jayris1f@hexun.com",
    "gender": "Male",
    "ip_address": "23.36.46.28"
  }, {
    "id": 53,
    "first_name": "Mano",
    "last_name": "Sprules",
    "email": "msprules1g@ocn.ne.jp",
    "gender": "Male",
    "ip_address": "249.187.251.189"
  }, {
    "id": 54,
    "first_name": "Lammond",
    "last_name": "Francecione",
    "email": "lfrancecione1h@ebay.com",
    "gender": "Male",
    "ip_address": "122.36.89.212"
  }, {
    "id": 55,
    "first_name": "Susannah",
    "last_name": "Angear",
    "email": "sangear1i@simplemachines.org",
    "gender": "Female",
    "ip_address": "80.190.194.153"
  }, {
    "id": 56,
    "first_name": "Tadd",
    "last_name": "Vanderplas",
    "email": "tvanderplas1j@jiathis.com",
    "gender": "Male",
    "ip_address": "118.237.218.19"
  }, {
    "id": 57,
    "first_name": "Colver",
    "last_name": "Passler",
    "email": "cpassler1k@netlog.com",
    "gender": "Male",
    "ip_address": "45.19.96.90"
  }, {
    "id": 58,
    "first_name": "Magnum",
    "last_name": "MacMeeking",
    "email": "mmacmeeking1l@comsenz.com",
    "gender": "Male",
    "ip_address": "220.200.141.204"
  }, {
    "id": 59,
    "first_name": "Suzann",
    "last_name": "Diviny",
    "email": "sdiviny1m@joomla.org",
    "gender": "Female",
    "ip_address": "158.129.165.35"
  }, {
    "id": 60,
    "first_name": "Arvin",
    "last_name": "Carrett",
    "email": "acarrett1n@plala.or.jp",
    "gender": "Male",
    "ip_address": "238.38.16.91"
  }, {
    "id": 61,
    "first_name": "Jefferson",
    "last_name": "Polak",
    "email": "jpolak1o@huffingtonpost.com",
    "gender": "Male",
    "ip_address": "173.134.222.49"
  }, {
    "id": 62,
    "first_name": "Alissa",
    "last_name": "Pawlick",
    "email": "apawlick1p@phoca.cz",
    "gender": "Female",
    "ip_address": "166.119.168.182"
  }, {
    "id": 63,
    "first_name": "Lek",
    "last_name": "Abramski",
    "email": "labramski1q@jimdo.com",
    "gender": "Male",
    "ip_address": "50.58.95.48"
  }, {
    "id": 64,
    "first_name": "Dallas",
    "last_name": "Cuerda",
    "email": "dcuerda1r@nationalgeographic.com",
    "gender": "Male",
    "ip_address": "216.45.159.120"
  }, {
    "id": 65,
    "first_name": "Dorian",
    "last_name": "Cokly",
    "email": "dcokly1s@rakuten.co.jp",
    "gender": "Male",
    "ip_address": "86.213.99.178"
  }, {
    "id": 66,
    "first_name": "Cchaddie",
    "last_name": "Rigg",
    "email": "crigg1t@ask.com",
    "gender": "Male",
    "ip_address": "221.40.117.82"
  }, {
    "id": 67,
    "first_name": "Reagan",
    "last_name": "Behrens",
    "email": "rbehrens1u@flavors.me",
    "gender": "Male",
    "ip_address": "227.101.140.248"
  }, {
    "id": 68,
    "first_name": "Wynn",
    "last_name": "Lesslie",
    "email": "wlesslie1v@goo.gl",
    "gender": "Male",
    "ip_address": "77.219.18.26"
  }, {
    "id": 69,
    "first_name": "Gibb",
    "last_name": "Rassmann",
    "email": "grassmann1w@dmoz.org",
    "gender": "Male",
    "ip_address": "214.81.106.2"
  }, {
    "id": 70,
    "first_name": "Carmita",
    "last_name": "Niese",
    "email": "cniese1x@bbb.org",
    "gender": "Female",
    "ip_address": "26.22.69.165"
  }, {
    "id": 71,
    "first_name": "Fifine",
    "last_name": "Keach",
    "email": "fkeach1y@geocities.jp",
    "gender": "Female",
    "ip_address": "84.239.202.126"
  }, {
    "id": 72,
    "first_name": "Nataline",
    "last_name": "Higbin",
    "email": "nhigbin1z@ifeng.com",
    "gender": "Female",
    "ip_address": "140.219.43.112"
  }, {
    "id": 73,
    "first_name": "Dannye",
    "last_name": "Rauprich",
    "email": "drauprich20@bbb.org",
    "gender": "Female",
    "ip_address": "115.32.182.223"
  }, {
    "id": 74,
    "first_name": "Kacy",
    "last_name": "Callaway",
    "email": "kcallaway21@shareasale.com",
    "gender": "Female",
    "ip_address": "0.68.28.243"
  }, {
    "id": 75,
    "first_name": "Nicolette",
    "last_name": "Robley",
    "email": "nrobley22@sciencedirect.com",
    "gender": "Female",
    "ip_address": "196.150.188.111"
  }, {
    "id": 76,
    "first_name": "Nikaniki",
    "last_name": "Breddy",
    "email": "nbreddy23@deviantart.com",
    "gender": "Female",
    "ip_address": "92.199.69.203"
  }, {
    "id": 77,
    "first_name": "Kimbra",
    "last_name": "McGillivrie",
    "email": "kmcgillivrie24@squarespace.com",
    "gender": "Female",
    "ip_address": "30.179.119.195"
  }, {
    "id": 78,
    "first_name": "Heall",
    "last_name": "Colerick",
    "email": "hcolerick25@parallels.com",
    "gender": "Male",
    "ip_address": "117.191.4.1"
  }, {
    "id": 79,
    "first_name": "Freddie",
    "last_name": "Shirtliff",
    "email": "fshirtliff26@csmonitor.com",
    "gender": "Female",
    "ip_address": "59.42.216.232"
  }, {
    "id": 80,
    "first_name": "Ambrose",
    "last_name": "Whapham",
    "email": "awhapham27@163.com",
    "gender": "Male",
    "ip_address": "115.58.94.132"
  }, {
    "id": 81,
    "first_name": "Crichton",
    "last_name": "Wanjek",
    "email": "cwanjek28@themeforest.net",
    "gender": "Male",
    "ip_address": "153.17.69.96"
  }, {
    "id": 82,
    "first_name": "Neville",
    "last_name": "Jiggens",
    "email": "njiggens29@apple.com",
    "gender": "Male",
    "ip_address": "239.45.154.57"
  }, {
    "id": 83,
    "first_name": "Valera",
    "last_name": "Slate",
    "email": "vslate2a@wordpress.com",
    "gender": "Female",
    "ip_address": "101.51.39.139"
  }, {
    "id": 84,
    "first_name": "Xavier",
    "last_name": "Peeters",
    "email": "xpeeters2b@cyberchimps.com",
    "gender": "Male",
    "ip_address": "254.145.27.233"
  }, {
    "id": 85,
    "first_name": "Ase",
    "last_name": "Orrin",
    "email": "aorrin2c@umich.edu",
    "gender": "Male",
    "ip_address": "141.193.159.84"
  }, {
    "id": 86,
    "first_name": "Cindee",
    "last_name": "Cockling",
    "email": "ccockling2d@boston.com",
    "gender": "Female",
    "ip_address": "29.135.117.64"
  }, {
    "id": 87,
    "first_name": "Oswald",
    "last_name": "Oxford",
    "email": "ooxford2e@yahoo.co.jp",
    "gender": "Male",
    "ip_address": "216.37.12.36"
  }, {
    "id": 88,
    "first_name": "Jeni",
    "last_name": "Triplow",
    "email": "jtriplow2f@nytimes.com",
    "gender": "Female",
    "ip_address": "173.193.130.152"
  }, {
    "id": 89,
    "first_name": "Kaye",
    "last_name": "Muschette",
    "email": "kmuschette2g@etsy.com",
    "gender": "Female",
    "ip_address": "64.224.104.57"
  }, {
    "id": 90,
    "first_name": "Clea",
    "last_name": "Tomaskov",
    "email": "ctomaskov2h@csmonitor.com",
    "gender": "Female",
    "ip_address": "152.149.153.90"
  }, {
    "id": 91,
    "first_name": "Drew",
    "last_name": "Cottis",
    "email": "dcottis2i@theatlantic.com",
    "gender": "Male",
    "ip_address": "253.7.127.138"
  }, {
    "id": 92,
    "first_name": "Farand",
    "last_name": "Slate",
    "email": "fslate2j@nsw.gov.au",
    "gender": "Female",
    "ip_address": "247.170.34.96"
  }, {
    "id": 93,
    "first_name": "Kenton",
    "last_name": "Hounson",
    "email": "khounson2k@shop-pro.jp",
    "gender": "Male",
    "ip_address": "203.147.232.219"
  }, {
    "id": 94,
    "first_name": "Rodolph",
    "last_name": "Gooding",
    "email": "rgooding2l@lulu.com",
    "gender": "Male",
    "ip_address": "82.193.24.1"
  }, {
    "id": 95,
    "first_name": "Ilaire",
    "last_name": "Dunham",
    "email": "idunham2m@cyberchimps.com",
    "gender": "Male",
    "ip_address": "14.180.16.116"
  }, {
    "id": 96,
    "first_name": "Alida",
    "last_name": "Raynes",
    "email": "araynes2n@seesaa.net",
    "gender": "Female",
    "ip_address": "182.102.74.44"
  }, {
    "id": 97,
    "first_name": "Damian",
    "last_name": "MacGillivray",
    "email": "dmacgillivray2o@chron.com",
    "gender": "Male",
    "ip_address": "106.122.227.255"
  }, {
    "id": 98,
    "first_name": "Redford",
    "last_name": "Strognell",
    "email": "rstrognell2p@cyberchimps.com",
    "gender": "Male",
    "ip_address": "186.255.245.197"
  }, {
    "id": 99,
    "first_name": "Lamont",
    "last_name": "Roony",
    "email": "lroony2q@51.la",
    "gender": "Male",
    "ip_address": "202.161.35.204"
  }, {
    "id": 100,
    "first_name": "Wash",
    "last_name": "Maskall",
    "email": "wmaskall2r@walmart.com",
    "gender": "Male",
    "ip_address": "200.188.107.232"
  }];